services:
  db:
    image: postgres:16-alpine
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: logsflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

volumes:
  pgdata: